# Configuración de permisos más restrictivos de los que hay por defecto
name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
# También se puede añadir la key permissions a nivel de workflow para que se aplique para todos los jobs
jobs:
  assign-label:
    # Este Workflow, que añade el label bug interactua con el API de GitHub, en concreto con el API issues
    # para editar el label del issue
    # Ahora mismo este Workflow no indica nada sobre permisos, pero se puede ser más restrictivo, porque
    # este Workflow realmente solo necesita permisos para interactuar con issues pero no necesita permisos
    # para interactuar con pull request o cambiar actions.
    # Con GitHub Actions es muy fácil controlar permisos con la key permissions
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # Aquí permisos a nivel de job.
    # Indicar que con estos permisos también estamos más seguros a la hora de evitar inyección de scripts
    permissions:
      # Indicando issues a write se indica que se puede escribir en issues, pero no se puede explorar el código
      # del repositorio por ejemplo.
      # issues: write
      # Cambiando el permiso a read
      issues: read
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        # Otra forma de evitar inyección de código malicioso con un if
        if: contains(github.event.issue.title, 'bug')
        # Una cosa importante a añadir es el Token secrets.GITHUB_TOKEN
        # Este secret no está informado en Settings > Secrets > Actions
        # De dónde viene entonces?
        # Es generado automáticamente por GitHub porque para asignar esta petición a la API de GitHub
        # debemos autenticar la petición. En otro caso cualquier persona podría enviar una petición a la API
        # para editar o borrar el issue.
        # Ese token generado por GitHub esta disponible para los jobs de este workflow y solo es válido hasta
        # que terminan los jobs. El token será eliminado por GitHub una vez el trabajo se ha ejecutado.
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail
